# Gemini Pro 配置
# 继承自 provider/gemini/common.yaml

model_type: gemini
model_name: gemini-pro
provider: gemini
base_url: "https://generativelanguage.googleapis.com/v1"
api_key: "${GEMINI_API_KEY}"
token_counter: gemini_pro

# 只覆盖需要修改的参数，其他从common.yaml继承
parameters:
  # 基础生成参数（覆盖common.yaml中的默认值）
  temperature: 0.7
  max_tokens: 2048
  top_p: 1.0
  top_k: 40
  
  # 其他参数保持默认值，无需重复配置

# 缓存配置继承自provider配置，可以覆盖
supports_caching: true  # Gemini明确支持缓存API

# 降级配置
fallback_enabled: true
fallback_models:
  - openai-gpt3.5-turbo
max_fallback_attempts: 3

# 元数据
metadata:
  provider: google
  version: "1.0"
  description: "Google Gemini Pro 模型"
  model_family: "gemini"