name: plan_execute_agent_workflow
description: 基于Plan-Execute Agent的工作流配置
version: 1.0

state_schema:
  name: PlanExecuteWorkflowState
  fields:
    workflow_messages:
      type: List[dict]
      default: []
      description: 工作流消息历史
    workflow_tool_calls:
      type: List[dict]
      default: []
      description: 工作流工具调用
    workflow_tool_results:
      type: List[dict]
      default: []
      description: 工作流工具结果
    workflow_iteration_count:
      type: int
      default: 0
      description: 工作流迭代计数
    workflow_max_iterations:
      type: int
      default: 10
      description: 工作流最大迭代次数
    task_history:
      type: List[dict]
      default: []
      description: 任务历史
    workflow_errors:
      type: List[dict]
      default: []
      description: 工作流错误列表
    context:
      type: Dict[str, Any]
      default: {}
      description: 上下文信息
    current_task:
      type: str
      default: ""
      description: 当前任务

nodes:
  plan_execute_agent:
    type: plan_execute_agent_node
    config:
      name: plan_execute_agent
      system_prompt: 你是一个使用Plan-Execute算法的智能助手，先制定计划然后逐步执行。
      max_iterations: 10
      max_steps: 5
      tools: [calculator, search, database]
      llm_client: mock
      next_node_on_complete: final_summary
      next_node_on_error: error_handler
      continue_on_plan_generated: true
    description: Plan-Execute Agent节点，制定和执行计划

  plan_review:
    type: llm_node
    config:
      llm_client: mock
      system_prompt: 审查生成的计划是否合理，并提供改进建议。
      max_tokens: 800
      temperature: 0.2
    description: 计划审查节点

  final_summary:
    type: llm_node
    config:
      llm_client: mock
      system_prompt: 总结整个计划执行过程，包括计划步骤、执行结果和最终结论。
      max_tokens: 1500
      temperature: 0.3
    description: 生成最终总结

  error_handler:
    type: llm_node
    config:
      llm_client: mock
      system_prompt: 处理计划执行过程中发生的错误，并提供恢复建议。
      max_tokens: 500
      temperature: 0.1
    description: 错误处理节点

edges:
  - from: plan_execute_agent
    to: plan_execute_agent  # 条件边需要to字段，但实际由path_map决定
    type: conditional
    condition: plan_execute_router
    path_map:
      plan_review: plan_review
      final_summary: final_summary
      error_handler: error_handler
      continue: plan_execute_agent
    description: Plan-Execute Agent路由

  - from: plan_review
    to: plan_execute_agent
    type: simple
    description: 计划审查后继续执行

  - from: final_summary
    to: __end__
    type: simple
    description: 工作流结束

  - from: error_handler
    to: __end__
    type: simple
    description: 错误处理后结束工作流

entry_point: plan_execute_agent

additional_config:
  max_execution_time: 600
  enable_logging: true
  plan_max_steps: 5
  recursion_limit: 10  # 限制递归深度防止内存泄漏
  memory_threshold_mb: 300  # 内存使用阈值
  max_message_history: 10  # 最大消息历史数量