# Hash转换工具配置
name: hash_convert
tool_type: builtin
description: 将文本转换为各种哈希值的工具，支持MD5、SHA1、SHA256、SHA512算法
function_path: defination.tools.hash_convert:hash_convert
enabled: true
timeout: 10
parameters_schema:
  type: object
  properties:
    text:
      type: string
      description: 要转换为哈希值的文本
    algorithm:
      type: string
      description: 哈希算法，可选值：md5, sha1, sha256, sha512
      enum: ["md5", "sha1", "sha256", "sha512"]
      default: "sha256"
  required:
    - text
metadata:
  category: "utility"
  tags: ["hash", "security", "encryption", "utility"]
  documentation_url: "https://docs.python.org/3/library/hashlib.html"