# Gemini Pro 配置
model_type: gemini
model_name: gemini-pro
base_url: "https://generativelanguage.googleapis.com/v1"
api_key: "${GEMINI_API_KEY}"
group: gemini_group

parameters:
  # 基础生成参数
  temperature: 0.7
  max_tokens: 2048
  max_output_tokens: null  # 最大输出token数
  top_p: 1.0
  top_k: 40
  
  # 停止序列
  stop_sequences: null  # 字符串数组
  
  # 候选数量
  candidate_count: 1  # 生成候选响应的数量
  
  # 系统指令
  system_instruction: null  # 系统指令配置
  
  # 响应MIME类型
  response_mime_type: null  # 如 "application/json", "text/plain"
  
  # 思考配置（新模型支持）
  thinking_config: null  # {"thinking_budget": integer}
  
  # 流式控制
  stream: false
  
  # 安全设置
  safety_settings: null  # 安全配置
  
  # 工具调用参数
  tool_choice: null  # 工具选择配置
  tools: null  # 工具列表
  
  # 其他参数
  user: null  # 用户标识符
  
  # 连接参数
  timeout: 30
  max_retries: 3

# 降级配置
fallback_enabled: true
fallback_models:
  - openai-gpt3.5-turbo
max_fallback_attempts: 3

# 元数据
metadata:
  provider: google
  version: "1.0"
  description: "Google Gemini Pro 模型"