# Gemini Pro 配置
model_type: gemini
model_name: gemini-pro
base_url: "https://generativelanguage.googleapis.com/v1"
api_key: "${GEMINI_API_KEY}"
group: gemini_group

parameters:
  temperature: 0.7
  max_tokens: 2048
  top_p: 1.0
  top_k: 40
  timeout: 30
  max_retries: 3
  stream: false

# 降级配置
fallback_enabled: true
fallback_models:
  - openai-gpt3.5-turbo
max_fallback_attempts: 3

# 元数据
metadata:
  provider: google
  version: "1.0"
  description: "Google Gemini Pro 模型"