# OpenAI GPT-4 配置
model_type: openai
model_name: gpt-4
base_url: "https://api.openai.com/v1"
api_key: "${OPENAI_API_KEY}"
group: openai_group

parameters:
  # 基础生成参数
  temperature: 0.7
  max_tokens: 2000
  max_completion_tokens: null  # 新增：最大完成token数
  top_p: 1.0
  
  # 惩罚参数
  frequency_penalty: 0.0
  presence_penalty: 0.0
  
  # 停止序列
  stop: null  # 可以是字符串、字符串数组或null，最多4个序列
  
  # 采样和概率参数
  top_logprobs: null  # 0-20之间，返回每个token位置的最可能token及其对数概率
  
  # 工具调用参数
  tool_choice: null  # "none", "auto", "required" 或特定工具对象
  tools: null  # 工具列表
  
  # 响应格式
  response_format: null  # {"type": "json_object"} 或 {"type": "json_schema", "json_schema": {...}}
  
  # 流式和控制参数
  stream: false
  stream_options: null  # 流式选项，仅在stream: true时设置
  
  # 服务和安全参数
  service_tier: "auto"  # "auto", "default", "flex", "priority"
  safety_identifier: null  # 用户标识符的哈希值
  store: false  # 是否存储输出用于模型蒸馏
  
  # 推理参数（新模型）
  reasoning: null  # {"effort": "low"|"medium"|"high"|"minimal"}
  
  # 详细程度控制
  verbosity: "medium"  # "low", "medium", "high"
  
  # 网络搜索选项
  web_search_options: null
  
  # 其他参数
  seed: null  # 已弃用，确定性采样
  user: null  # 已弃用，被safety_identifier替代
  
  # 连接参数
  timeout: 30
  max_retries: 3

# 降级配置
fallback_enabled: true
fallback_models:
  - openai-gpt3.5-turbo
max_fallback_attempts: 3

# 元数据
metadata:
  provider: openai
  version: "1.0"
  description: "OpenAI GPT-4 模型"