# OpenAI GPT-4 配置
model_type: openai
model_name: gpt-4
base_url: "https://api.openai.com/v1"
api_key: "${OPENAI_API_KEY}"
group: openai_group

parameters:
  temperature: 0.7
  max_tokens: 2000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout: 30
  max_retries: 3
  stream: false

# 降级配置
fallback_enabled: true
fallback_models:
  - openai-gpt3.5-turbo
max_fallback_attempts: 3

# 元数据
metadata:
  provider: openai
  version: "1.0"
  description: "OpenAI GPT-4 模型"