# Anthropic Claude Token计数器配置
model_type: anthropic
model_name: claude-3-sonnet-20240229
enhanced: true
group: anthropic_group

# 元数据
metadata:
  provider: anthropic
  version: "2.0"
  description: "Anthropic Claude Token计数器"