# OpenAI GPT-4 配置
# 继承自 provider/openai/common.yaml

model_type: openai
model_name: gpt-4
provider: openai
base_url: "https://api.openai.com/v1"
api_key: "${OPENAI_API_KEY}"
token_counter: openai_gpt4

# 继承provider通用配置，只覆盖特定参数
parameters:
  # 基础生成参数（覆盖common.yaml中的默认值）
  temperature: 0.7
  max_tokens: 2000
  max_completion_tokens: null
  top_p: 1.0
  
  # 惩罚参数
  frequency_penalty: 0.0
  presence_penalty: 0.0
  
  # 停止序列
  stop: null
  
  # 采样和概率参数
  top_logprobs: null
  
  # 工具调用参数
  tool_choice: null
  tools: null
  
  # 响应格式
  response_format: null
  
  # 流式和控制参数
  stream: false
  stream_options: null
  
  # 服务和安全参数
  service_tier: "auto"
  safety_identifier: null
  store: false
  
  # 推理参数（新模型）
  reasoning: null
  
  # 详细程度控制
  verbosity: "medium"
  
  # 网络搜索选项
  web_search_options: null
  
  # 其他参数
  seed: null
  user: null
  
  # 连接参数
  timeout: 30
  max_retries: 3

# 缓存配置（继承自provider配置）
supports_caching: false  # OpenAI不直接支持API级缓存
cache_config:
  enabled: false
  ttl_seconds: 3600
  max_size: 1000

# 降级配置
fallback_enabled: true
fallback_models:
  - openai-gpt3.5-turbo
max_fallback_attempts: 3

# 元数据
metadata:
  provider: openai
  version: "1.0"
  description: "OpenAI GPT-4 模型"
  model_family: "gpt-4"
  capabilities:
    - text_generation
    - function_calling
    - streaming
    - vision
  limitations:
    - no_api_caching