# 应用程序配置
version: "1.0"

# 应用程序基本信息
application:
  name: "ModularAgent"
  version: "1.0.0"
  environment: "${ENV:development}"
  description: "模块化智能体框架"

# 组件配置 - 简化的配置驱动组装
components:
  # LLM配置
  llm:
    config_path: "configs/llms"
    default_provider: "openai"
    
  # 工具配置
  tools:
    config_path: "configs/tools"
    auto_discovery: true
    
  # Agent配置
  agents:
    config_path: "configs/agents"
    default_type: "react"
    
  # 工作流配置
  workflows:
    config_path: "configs/workflows"
    template_path: "configs/workflows/_templates.yaml"
    
  # 会话配置
  sessions:
    storage_type: "file"
    storage_path: "sessions"
    auto_save: true

# 依赖注入配置
dependencies:
  # 单例服务
  singletons:
    - "IConfigLoader"
    - "ILLMClientFactory"
    - "IToolManager"
    - "IAgentFactory"
    - "ISessionStore"
    - "IWorkflowManager"
    
  # 作用域服务
  scoped:
    - "IWorkflowBuilder"
    - "ISessionManager"
    - "IAgentManager"

# 环境特定配置
environments:
  development:
    log_level: "DEBUG"
    hot_reload: true
    debug: true
    
  testing:
    log_level: "INFO"
    hot_reload: false
    debug: true
    
  production:
    log_level: "WARNING"
    hot_reload: false
    debug: false

# 启动配置
startup:
  # 自动注册的服务
  auto_register:
    - "workflow_templates"
    - "agent_types"
    - "tool_types"
  
  # 健康检查
  health_check:
    enabled: true
    endpoints:
      - "/health"
      - "/ready"
      - "/metrics"
  
  # 启动钩子
  hooks:
    before_startup:
      - "validate_configuration"
      - "initialize_logging"
    after_startup:
      - "register_signal_handlers"
      - "start_background_tasks"

# 性能配置
performance:
  # 缓存配置
  cache:
    enabled: true
    ttl: 3600  # 1小时
    max_size: 1000
  
  # 连接池配置
  connection_pool:
    max_connections: 10
    timeout: 30
  
  # 异步配置
  async:
    max_workers: 4
    queue_size: 100

# 安全配置
security:
  # 密钥管理
  secrets:
    provider: "environment"
    prefix: "AGENT_"
  
  # 访问控制
  access_control:
    enabled: false
    default_policy: "allow"