thread_features:
  branching:
    enabled: true
    max_branches_per_thread: 10
  snapshots:
    enabled: true
    auto_snapshot_interval: 3600  # 1小时
  rollback:
    enabled: true
    max_history_days: 30
  collaboration:
    enabled: false  # 默认禁用，需要显式开启