# 工具集组配置
basic_tools:
  tools: ["search", "calculator", "weather"]
  timeout: 30
  max_retries: 3

code_analysis:
  tools: ["code_parser", "syntax_checker", "complexity_analyzer"]
  timeout: 60
  max_retries: 2

file_operations:
  tools: ["file_reader", "file_writer", "directory_browser"]
  timeout: 45
  max_retries: 3

data_processing:
  tools: ["csv_reader", "data_cleaner", "statistical_analyzer"]
  timeout: 120
  max_retries: 2

visualization:
  tools: ["chart_generator", "plot_creator", "dashboard_builder"]
  timeout: 90
  max_retries: 2