# Hook组配置
# 定义各种Hook类型的默认配置

# 死循环检测Hook组配置
dead_loop_detection_group:
  enabled: true
  config:
    max_iterations: 20
    fallback_node: "dead_loop_check"
    log_level: "WARNING"
    check_interval: 1
    reset_on_success: true

# 性能监控Hook组配置
performance_monitoring_group:
  enabled: true
  config:
    timeout_threshold: 10.0
    log_slow_executions: true
    metrics_collection: true
    slow_execution_threshold: 5.0
    enable_profiling: false

# 错误恢复Hook组配置
error_recovery_group:
  enabled: true
  config:
    max_retries: 3
    fallback_node: "error_handler"
    retry_delay: 1.0
    exponential_backoff: true
    retry_on_exceptions: ["Exception"]

# 日志Hook组配置
logging_group:
  enabled: true
  config:
    log_level: "INFO"
    structured_logging: true
    log_execution_time: true
    log_state_changes: false
    log_format: "json"

# 指标收集Hook组配置
metrics_collection_group:
  enabled: true
  config:
    enable_performance_metrics: true
    enable_business_metrics: true
    enable_system_metrics: false
    metrics_endpoint: null
    collection_interval: 60